### ISSUE TITLE
Change static header to dynamic header.

### ISSUE THREAD

**Issue by markan2ny** [markan2ny/aven-gate-pass#1]
- [x] Apply Blade Components

**Comment by markan2ny** [comment]
I'am working on it. :)

**Comment by mayurstwt** [comment]
I would love to work on this issue would you assign me this issue with available resources ?

**Comment by markan2ny** [comment]
> mayurstwt

Thank you for interesting my small project and I really appreciate it. but this is a practice purpose only.

**Comment by mayurstwt** [comment]
ok no problem
